project:
  type: book

book:
  title: "Diseño de IU/UX para un Juego"
  author: "Luis Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - userStories.qmd
    - reqDesign.qmd
    - esqueleto.qmd
    - iterativo.qmd
    - metodoDesign.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml
